# Generated by Django 5.0.6 on 2024-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreLibros', '0002_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cantidad',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
